language: java

install:
  - export VERSION=8.1.1
  - export GRADLE_DIR=/tmp/gradle
  - wget https://services.gradle.org/distributions/gradle-${VERSION}-bin.zip
  - mkdir ${GRADLE_DIR}
  - unzip -d ${GRADLE_DIR} gradle-${VERSION}-bin.zip
  - export PATH=${GRADLE_DIR}/gradle-${VERSION}/bin:$PATH
  - gradle -v

dist: xenial

os:
  - linux
  - osx
  - windows

jdk:
  - openjdk21
  - openjdk20
  - openjdk19
  - openjdk18
  - openjdk17
  - openjdk16
  - openjdk15
  - openjdk14
  - openjdk13
  - openjdk12
  - openjdk11

jobs:
  allow_failures:
    - jdk: openjdk21
