language: java

install:
  - export VERSION=7.0
  - export GRADLE_DIR=/tmp/gradle
  - wget https://services.gradle.org/distributions/gradle-${VERSION}-bin.zip
  - mkdir ${GRADLE_DIR}
  - unzip -d ${GRADLE_DIR} gradle-${VERSION}-bin.zip
  - export PATH=${GRADLE_DIR}/gradle-${VERSION}/bin:$PATH
  - gradle -v

dist: xenial

os:
  - linux
  - osx

jdk:
  - openjdk17
  - openjdk16
  - openjdk15
  - openjdk14
  - openjdk13
  - openjdk12
  - openjdk11
  - openjdk8

jobs:
  allow_failures:
    - os: osx
      jdk: openjdk8
    - jdk: openjdk17
