language: java

matrix:
  include:
    - os: linux
      dist: trusty
      jdk: oraclejdk8
    - os: linux
      dist: trusty
      jdk: oraclejdk9
    - os: osx
      osx_image: xcode9.1

script:
  - make
  - make test
