language: java
dist: xenial

install:
  - export VERSION=5.0
  - wget https://services.gradle.org/distributions/gradle-${VERSION}-bin.zip
  - mkdir /tmp/gradle
  - unzip -d /tmp/gradle gradle-${VERSION}-bin.zip
  - export PATH=/tmp/gradle/gradle-${VERSION}/bin:$PATH
  - gradle -v

matrix:
  include:
    - os: osx
      osx_image: xcode9.2
      env:
        - ==JAVA 1.8.0_112==
    - os: osx
      osx_image: xcode10
      env:
        - ==JAVA 10.0.2==
    - os: osx
      osx_image: xcode10.1
      env:
        - ==JAVA 11.0.1==
    - os: linux
      jdk: openjdk8
    - os: linux
      jdk: openjdk9
    - os: linux
      jdk: openjdk10
    - os: linux
      jdk: openjdk11
    - os: linux
      jdk: oraclejdk8
    - os: linux
      jdk: oraclejdk9
    # - os: linux
    #   jdk: oraclejdk10
    - os: linux
      jdk: oraclejdk11
