language: java

install:
  - wget https://services.gradle.org/distributions/gradle-4.4-bin.zip
  - mkdir /tmp/gradle
  - unzip -d /tmp/gradle gradle-4.4-bin.zip
  - export PATH=/tmp/gradle/gradle-4.4/bin:$PATH
  - gradle -v

script:
  - ./prepare.sh
  - ./test.sh

matrix:
  include:
    - os: linux
      dist: trusty
      jdk: oraclejdk8
    - os: linux
      dist: trusty
      jdk: oraclejdk9
    - os: osx
      osx_image: xcode9.2
