environment:
  matrix:
  - JAVA_HOME: C:\Program Files\Java\jdk1.8.0
  - JAVA_HOME: C:\Program Files\Java\jdk9
  - JAVA_HOME: C:\Program Files\Java\jdk10
  - JAVA_HOME: C:\Program Files\Java\jdk11

install:
  - choco install gradle
  - gradle --version

build_script:
  - gradle assemble --no-daemon

test_script:
  - gradle check --no-daemon

cache:
  - C:\Users\appveyor\.gradle
