environment:
  matrix:
    - JAVA_HOME: C:\Program Files\Java\jdk1.8.0
    - JAVA_HOME: C:\Program Files\Java\jdk9
    - JAVA_HOME: C:\Program Files\Java\jdk10
    - JAVA_HOME: C:\Program Files\Java\jdk11
    - JAVA_HOME: C:\Program Files\Java\jdk12
    - JAVA_HOME: C:\Program Files\Java\jdk13

install:
  - set VERSION=6.0
  - set GRADLE_DIR=C:\gradle
  - set DOWNLOAD_URL=https://services.gradle.org/distributions/gradle-%VERSION%-bin.zip
  - ps: wget $env:DOWNLOAD_URL -O gradle-bin.zip
  - mkdir %GRADLE_DIR%
  - 7z x gradle-bin.zip -o%GRADLE_DIR%
  - set PATH=%GRADLE_DIR%\gradle-%VERSION%\bin;%PATH%
  - gradle -v

build_script:
  - gradle assemble --no-daemon

test_script:
  - gradle check --no-daemon

cache:
  - C:\Users\appveyor\.gradle
