name: Coverity Scan

on:
  schedule:
    - cron: '0 0 * * *'  # Every day at 00:00 UTC
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  daily_scan:
    name: Daily Scan
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout Code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1
        with:
          persist-credentials: false

      - name: Set up JDK 21
        uses: actions/setup-java@de7274f081f381c8f8158605e0321c36c376e2e6  # v6.0.1
        with:
          distribution: 'zulu'
          java-version: 21

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@9c971963bec38e04b3d30dcc455b5382be2fdbfb  # v6.3.0
        with:
          gradle-version: "9.7.1"

      - name: Run Coverity Scan
        uses: vapier/coverity-scan-action@8fe7b0af23cbbd4eced5f63dcd2384640eaa5d49  # v1.10.0
        with:
          project: Zialus/SD-DistributedFileSystem
          token: ${{ secrets.COVERITY_TOKEN }}
          email: raulmendesferreira@gmail.com
          build_language: java
          command: gradle build --no-daemon
          version: trunk
          description: SD-DistributedFileSystem
