name: Coverity Scan
on:
  schedule:
    - cron: '0 0 * * *' # Every day at 00:00 UTC

  workflow_dispatch:

jobs:
  daily_scan:
    name: Daily Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Download Coverity Build Tool
        run: |
          wget -q https://scan.coverity.com/download/java/linux64 --post-data "token=$TOKEN&project=Zialus%2FSD-DistributedFileSystem" -O cov-analysis-linux64.tar.gz
          mkdir cov-analysis-linux64
          tar xzf cov-analysis-linux64.tar.gz --strip 1 -C cov-analysis-linux64
        env:
          TOKEN: ${{ secrets.COVERITY_TOKEN }}

      - name: Build with cov-build
        run: |
          export PATH=`pwd`/cov-analysis-linux64/bin:$PATH
          cov-build --dir cov-int gradle build --no-daemon

      - name: Submit the result to Coverity Scan
        run: |
          tar czvf snake.tgz cov-int
          curl \
          --form token=$TOKEN \
          --form email=raulmendesferreira@gmail.com \
          --form file=@snake.tgz \
          --form version="trunk" \
          --form description="SD-DistributedFileSystem" \
          https://scan.coverity.com/builds?project=Zialus%2FSD-DistributedFileSystem
        env:
          TOKEN: ${{ secrets.COVERITY_TOKEN }}
